### PR TITLE
Weather App JavaScript

### PR DESCRIPTION
**Pull request by carloshdelreal**
Weather App
- On this Application, you can get the current weather conditions of a city by typing it
- the application uses the https://openweathermap.org/ API to request the information and display it to the user
- You can pick the used scale for the temperature °C or °F

### CODE REVIEW

**Comment by carloshdelreal** [comment]
I am so sorry, I tried to solve the last two linting issues and could not do it

**Comment by carloshdelreal** [comment]
I tried to fix the last two linting problems and I can not do it, It is related to the use of the async keyword so, I submit the code anyway

**Comment by azdrenymeri** [comment]
### Hello @carloshdelreal  👋 
### Good job on this one 👍 
 - [ ] The user should be able to toggle the unit from Celcius to Fahrenheit and vice versa.
- [ ] Comments: It’s better to delete commented code.
* If I press enter without text inside the input field it throws an `Uncaught TypeError: Cannot read property 'cityInput' of null` error.
* Also if the city is not found it throws a `404` not found.
scr
#### Kindly handle these two errors and add it for another review.

**Comment by carloshdelreal** [comment]
Thank you, the change on the .stickler.yml file was the solution

**Pull request merged**
